# Generated by Django 5.1.5 on 2025-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_alter_factura_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='opcion_entrega',
            field=models.CharField(choices=[('RETIRO', 'Retiro'), ('ENVIO', 'Envio')], default='RETIRO', max_length=20),
        ),
    ]
